title: Christian Hernandez    
description: Portfolio and visual research archive
baseurl: "/christianhernandez"         # leave blank if deploying to root
url: https://chruhern.github.io/christianhernandez/  # your domain or GitHub Pages URL

markdown: kramdown

permalink: pretty   # clean URLs like /projects/

# Build settings
exclude:
  - README.md
  
